[project]
name = "streamlit-lectures"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.7",
    "scipy>=1.16.3",
    "streamlit>=1.52.0",
]
